spring:
  application:
    name: mc-acc

---
spring:
  profiles:
    active: PROD

  datasource:
    url: jdbc:postgresql://postgres:5432/account
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db.changelog/db.changelog-master.xml

  kafka:
    bootstrap-server: "kafka:9092"
    group-id: "dsf"

server:
  port: 34135

client:
  auth: "http://mc-auth:8081"

logging:
  level:
    org:
      springframework:
        cache: TRACE #логирование доступа к кешу
        transaction:
        #interceptor: trace
      hibernate:
        engine:
          transaction:
            internal:
              org.hibernate.engine.transaction.internal.TransactionImpl: debug
        SQL: trace #show sql in console
        type:
          descriptor:
            sql:
              BasicBinder: trace # see values
    root: info
---