spring:
  application:
    name: ACCOUNT-SERVICE

server:
  port: 34135

---
spring:
  profiles:
    active: PROD

  datasource:
    url: jdbc:postgresql://social-network-postgres:5432/account
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db.changelog/db.changelog-master.xml

  kafka:
    bootstrap-server: "social-network-kafka:9092"

client:
  auth: "http://mc-auth:8081"

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    org:
      springframework:
        cache: TRACE #логирование доступа к кешу
        transaction:
        #interceptor: trace
      hibernate:
        engine:
          transaction:
            internal:
              org.hibernate.engine.transaction.internal.TransactionImpl: debug
        SQL: trace #show sql in console
        type:
          descriptor:
            sql:
              BasicBinder: trace # see values
    root: info
---